### ISSUE TITLE
[VC START NOT KICKING BUG]

### ISSUE THREAD

**Issue by Yelloo5191** [School-Simplified/TutorVC#13]
**FILL OUT THE FIELDS BELOW!**

**Discord Username and Tag**
Yellooooooo#3477

**Describe the bug**
The bug occurs after joining the your VC and running the "+end" command whilst quickly joining "VC Start". The result is that the bot won't kick you out or move you to your own VC.

**To Reproduce**
Join VC Start to create your VC
Type +end and immediately move back to VC Start

**Expected behavior**
I would have expected the bot to have either Kicked me from "VC Start" or created a new VC and moved me into it

**Screenshots**
![image](https://user-images.githubusercontent.com/76452706/119723905-e4b27c00-be22-11eb-9f4d-7e4bb0256a77.png)

**Additional context**
N/a

**Comment by rohitp30** [comment]
Issue appears to already be fixed at the time of testing (5/29/2021)
