### ISSUE TITLE
[VC LOCKING OUT OWNER BUG]

### ISSUE THREAD

**Issue by Yelloo5191** [School-Simplified/TutorVC#15]
**FILL OUT THE FIELDS BELOW!**

**Discord Username and Tag**
Yellooooooo#3477

**Describe the bug**
A user is allowed to remove their own permissions to a locked VC meaning if they leave and try to rejoin said VC, they won't be able to and they cannot re-add their permissions without being in the VC.

**To Reproduce**
Join Start VC and make your own VC
Run `+lock` to lock the VC
Run `+permit remove <@your username>`
Leave the VC

**Expected behavior**
The bot shouldn't allow you to remove your own permissions to your own VC.

**Screenshots**
![image](https://user-images.githubusercontent.com/76452706/119726784-5b04ad80-be26-11eb-9e76-cb92aa64a4e4.png)

**Additional context**
N/a

**Comment by rohitp30** [comment]
Fixed in ed2c7e8
