### ISSUE TITLE
Vacation Sid [BUG]

### ISSUE THREAD

**Issue by mangoess** [School-Simplified/TutorVC#6]
**Discord Username and Tag**
mangoess#4904

**Describe the bug**
When doing the +permit list (Any user's mention)
It will show that "vacation sid" is one of them
no matter the user, no matter the role.

**To Reproduce**
Go to channel #control-panel (Channel id 843637802293788692)
Do " +permit list @ (any user's mention)
It will say vacation sid is an authorized user, even if
you didn't add them

**Expected behavior**
Expected behavior is ideally in a state that either lists the true authorized users,
or just brings up a message telling the user that they don't have any authorized users.

**Screenshots**
![image](https://user-images.githubusercontent.com/69760274/119346380-320bdd80-bcab-11eb-9385-d3d1d0f84541.png)

**Additional context**
User <@784409133071859762> (Discord is stATIC#9555 is not just a random person, it's an alt account for bug testing)
Frankly I'm unaware if authorized users are the staff that can access your voice channel but it says in the notion that
any staff member can access it, so I'm not sure why Sid is the only one in the list.

(I hope you have a great day!)

**Comment by rohitp30** [comment]
I figured out the issue, looks like the channel detection was hardcoded instead of fetching the channel from the member's current voice channel.

**Comment by mangoess** [comment]
Alright, nice to know, Will close it now
