### ISSUE TITLE
[BUG] Rename Command

### ISSUE THREAD

**Issue by mangoess** [School-Simplified/TutorVC#7]
**Discord Username and Tag**
mangoess#4904

**Describe the bug**
In #control-panel on the main SS server, when you start a VC by joining the channel it says "Available Commands" and has the rename command even though if you use it, you'll be behind a role barrier, even though it says "Available"

**To Reproduce**
Just make a vc and do the command, it's not rocket science
More detailed explanation:
You'll need an account that doesn't have the Server Booster/Academic Member/Legends role, it'll still present you with that command even though you can't use it

**Expected behavior**
I don't believe that there is a wrong way to fix this issue, my first thought was to just remove it from the message entirely but that's your call 😃 
but I do think that this is a good option
INSERT SOLUTION HERE:
Solution is in Screenshots.

**Screenshots**
![image](https://user-images.githubusercontent.com/69760274/119348597-253cb900-bcae-11eb-9f1d-dfeafa5b51a2.png)

**Additional context**
The image of the message is just a recreation.

**Comment by mangoess** [comment]
btw where it says
"Requires ROLE", "ROLE" is supposed to be the roles that can rename their channel.
so for example for server boosters it'd be
Requires SERVER BOOST
So that's what I mean by "ROLE"

**Comment by rohitp30** [comment]
I'll make it so it displays all the commands you can actually execute, maybe a strikethrough with a note saying you can't run `rename` since you don't have the proper roles.

**Comment by mangoess** [comment]
Nice, I'll close it now
