### ISSUE TITLE
"README" [FEATURE]

### ISSUE THREAD

**Issue by mangoess** [School-Simplified/TutorVC#9]
**Describe the Feature Update**
honestly I think Space is doing a lot of the work, and I think many of us are more then qualified to at least contribute a tiny bit, I suggest that we make a read me so devs and staff can contribute
because in all seriousness space is a manager, and from what im seeing he is doing more work on this project then he should be doing.

**Discord Username and Tag**
mangoess#4904

**Comment by mangoess** [comment]
"License" was a wrong title, I don't think we need to have a license considering this project is private

**Comment by rohitp30** [comment]
Yeah I'll draft one up soon, although I'll keep the issue open until I actually publish it.

**Comment by mangoess** [comment]
Ok! I hope that I can manage to contribute 😄
